language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
env:
  global:
    -secure: RD/Y9lHZzUUis7K/4Q/xIHdzJLmufMPOuICkGgowPSSxiLTUIJ8OTsDJRHLZG+qS+ZtsQgOHtVaTtVxd5XJbkf394ClL6FsCUBCA3m3ERAJrWzwANuSh0PQyZTFUskt9M63xHMKVLFyc6ny+/mwOsiIaZzuxB0p3gaxlSd3Hewc=
    -secure: RWyIHlrSrWicF0KYXRHm757MukSYDgAed/LWi/G4Ce3PoZXIJxFwjyAxGBuuOSmCqFv4tWNmnHN8S4y8aZ4L8qPB+VtCEXm+SooLWwOvZFyiVpz4qcP3Tnmxh4Cp3nbzNYjwjmYpvqWLB/4YiJD0A9aK1ryshipleF1x0V1V8hE=
